// <auto-generated />
using System;
using GameCollectionPlayApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameCollectionPlayApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126001938_TabelaGamePlanning")]
    partial class TabelaGamePlanning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GameCollectionPlayApi.Models.CompatibilidadeNotebookGamerAtual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("CompatibilidadeNotebookGamerAtual");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.CompatibilidadePcGamerAtual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("CompatibilidadePcGamerAtual");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompatibilidadeNotebookGamerAtualId")
                        .HasColumnType("int");

                    b.Property<int>("CompatibilidadePcGamerAtualId")
                        .HasColumnType("int");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoAdicional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LancamentoFlagId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonalRating")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CompatibilidadeNotebookGamerAtualId");

                    b.HasIndex("CompatibilidadePcGamerAtualId");

                    b.HasIndex("LancamentoFlagId");

                    b.HasIndex("StatusId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.GameGender", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "GenderId");

                    b.HasIndex("GenderId");

                    b.ToTable("GameGender");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.GamePlanning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FellPlayRating")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GameplayRating")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StatusGamePlanningId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusGamePlanningId");

                    b.ToTable("GamePlanning");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.GamePlatform", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("GamePlatform");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Gender");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.LancamentoFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("LancamentoFlag");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Platform");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.StatusGamePlanning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("StatusGamePlanning");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.Game", b =>
                {
                    b.HasOne("GameCollectionPlayApi.Models.CompatibilidadeNotebookGamerAtual", "CompatibilidadeNotebookGamerAtual")
                        .WithMany()
                        .HasForeignKey("CompatibilidadeNotebookGamerAtualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollectionPlayApi.Models.CompatibilidadePcGamerAtual", "CompatibilidadePcGamerAtual")
                        .WithMany()
                        .HasForeignKey("CompatibilidadePcGamerAtualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollectionPlayApi.Models.LancamentoFlag", "LancamentoFlag")
                        .WithMany()
                        .HasForeignKey("LancamentoFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollectionPlayApi.Models.Status", "Status")
                        .WithMany("Games")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompatibilidadeNotebookGamerAtual");

                    b.Navigation("CompatibilidadePcGamerAtual");

                    b.Navigation("LancamentoFlag");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.GameGender", b =>
                {
                    b.HasOne("GameCollectionPlayApi.Models.Game", "Game")
                        .WithMany("GameGenders")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollectionPlayApi.Models.Gender", "Gender")
                        .WithMany("GameGenders")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.GamePlanning", b =>
                {
                    b.HasOne("GameCollectionPlayApi.Models.StatusGamePlanning", "StatusGamePlanning")
                        .WithMany("GamePlanning")
                        .HasForeignKey("StatusGamePlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusGamePlanning");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.GamePlatform", b =>
                {
                    b.HasOne("GameCollectionPlayApi.Models.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollectionPlayApi.Models.Platform", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.Game", b =>
                {
                    b.Navigation("GameGenders");

                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.Gender", b =>
                {
                    b.Navigation("GameGenders");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.Platform", b =>
                {
                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.Status", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GameCollectionPlayApi.Models.StatusGamePlanning", b =>
                {
                    b.Navigation("GamePlanning");
                });
#pragma warning restore 612, 618
        }
    }
}
